#pragma once
#include <string>
#define ITEMBOX 3150
#define ITEMPOUCH 72

//Trying defines instead of a class
#define TOTAL_ITEM_BOX_SLOTS 1400
#define TOTAL_PALICO_EQUIPMENT_SLOTS 700
#define TOTAL_ITEM_SETS 8
#define INVENTORY_ITEM_SLOTS 32
#define TOTAL_PALICOS 60

#define SIZEOF_NAME 32
#define SIZEOF_PALICO_GREETINGS 60

#define SIZEOF_ITEM 18
#define SIZEOF_ITEMBOX 3150
#define SIZEOF_ITEMPOUCH 72
#define SIZEOF_EQUIPMENT 24
#define SIZEOF_PALICO 319
#define SIZEOF_GUILD_CARD 5208
#define SIZEOF_CRAFTABLE_ARMOR 392
#define SIZEOF_CRAFTABLE_WEAPON 40
#define SIZEOF_CRAFTABLE_PALICO_GEAR 104

#define SIZEOF_SHOUTOUT 104
#define SIZEOF_AUTOMATIC_SHOUTOUT 104
#define SIZEOF_GAME_SHOUTOUT 36

#define ITEM_PER_BOX 100
#define ITEM_PER_POUCH 8

#define TOTAL_CRAFTABLE_ARMOR_SHOPS 5
#define TOTAL_CRAFTABLE_WEAPON_SHOPS 14
#define TOTAL_EQSHOP_SHOPS 19
#define TOTAL_CRAFTABLE_PALICO_SHOPS 3

#define TOTAL_WEAPONS 15
#define TOTAL_MONSTERHUNTS 71

#define TOTAL_SHOUTOUTS 24
#define TOTAL_AUTOMATIC_SHOUTOUTS 9

using std::string;
/*
class Constants
{
	public:
    const string EDITOR_VERSION = "APM MHGen Save Editor v0.16c";

    const u16 TOTAL_ITEM_BOX_SLOTS = 1400;
    const u16 TOTAL_PALICO_EQUIPMENT_SLOTS = 700;
    const u16 TOTAL_ITEM_SETS = 8;
    const u16 INVENTORY_ITEM_SLOTS = 32;
    const u16 TOTAL_PALICOS = 60;

    const u16 SIZEOF_NAME = 32;
    const u16 SIZEOF_PALICO_GREETINGS = 60;

    const u16 SIZEOF_ITEM = 18;
    const u16 SIZEOF_ITEMBOX = 3150;
    const u16 SIZEOF_ITEMPOUCH = 72;
    const u16 SIZEOF_EQUIPMENT = 24;
    const u16 SIZEOF_PALICO = 319;
    const u16 SIZEOF_GUILD_CARD = 5208;
    const u16 SIZEOF_CRAFTABLE_ARMOR = 392;
    const u16 SIZEOF_CRAFTABLE_WEAPON = 40;
    const u16 SIZEOF_CRAFTABLE_PALICO_GEAR = 104;

    const u16 SIZEOF_SHOUTOUT = 104;
    const u16 SIZEOF_AUTOMATIC_SHOUTOUT = 104;
    const u16 SIZEOF_GAME_SHOUTOUT = 36;

    const u16 ITEM_PER_BOX = 100;
    const u16 ITEM_PER_POUCH = 8;

    const u32 TOTAL_CRAFTABLE_ARMOR_SHOPS = 5;
    const u16 TOTAL_CRAFTABLE_WEAPON_SHOPS = 14;
    const u16 TOTAL_EQSHOP_SHOPS = 19;
    const u16 TOTAL_CRAFTABLE_PALICO_SHOPS = 3;

    const u16 TOTAL_WEAPONS = 15;
    const u16 TOTAL_MONSTERHUNTS = 71;

    const u16 TOTAL_SHOUTOUTS = 24;
    const u16 TOTAL_AUTOMATIC_SHOUTOUTS = 9;
};*/